fix(ci): check return code on test docker run
timeout command causes return code 124 instead of 0, needed to handle that differently in the Actions environment

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -88,4 +88,9 @@ jobs:
 
     - name: Test app is running in Docker
       run: |
-        timeout 10 docker run -p 5000:5000 --name test-gas-prices-gr-api test-gas-prices-gr-api:latest
+        if [ timeout 10 docker run -p 5000:5000 --name test-gas-prices-gr-api test-gas-prices-gr-api:latest -eq 124 ]; then
+          echo "OK"
+        else
+          echo "Failed running Docker container"
+          exit 1
+        fi
